### ISSUE TITLE
I dont have time to input

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#126]
To avoid havig my AWS credentials in cleartext, I use https://github.com/99designs/aws-vault/ to store my credentials (which in turn relies on https://www.passwordstore.org/). In ~/.aws/config
```
[profile sandbox]
region=eu-central-1
credential_process=aws-vault export --format=json sandbox
# TODO record bitwarden device instead
mfa_serial = arn:aws:iam::REDACTED:mfa/teto
```

When assuming roles, I need to use MFA (multiple factor authentication) and input my credentials but novops wont let me because it times out after 5sec and I dont have time to fetch and input my MFA token.

```
$ novops load -e sandbox -s .envrc
✔ Select environment · sandbox
Enter MFA code for arn:aws:iam::REDACTED:mfa/bitwarden_2: Error: An error occured. Set environment variable RUST_LOG=[trace|debug|info|warn] or RUST_BACKTRACE=1 for more verbosity.

Caused by:
    0: Failed to load environment.
    1: Could not resolve AWS input AwsInput { assume_role: AwsAssumeRoleInput { role_arn: "arn:aws:iam::REDACTED:role/REDACTED", source_profile: Some("REDACTED") } }
    2: Couldn't impersonate role arn:aws:iam::REDACTED:role/REDACTED (session name: "REDACTED")
    3: dispatch failure
    4: other
    5: identity resolver timed out after 5s
 ```
 
 I thought it would be a nice scenario to share. For now I can just disable aws-vault for those times I need to use novops.

**Comment by PierreBeucher** [comment]
Well, that's an interesting hedge case ! Since aws-vault is widely used this seems like a nice feature, will do ;)

Thanks for the report

**Comment by PierreBeucher** [comment]
Will try to play with underlying's client timeout to solve this.

**Comment by PierreBeucher** [comment]
Done with https://github.com/PierreBeucher/novops/pull/127 - will come with next release, but you can enjoy it right now with Nix ;)

Use with:

```yaml
config:
  aws:
    identity_cache:
      load_timeout: 120 # Give user 2 min to enter TOTP
```

Actually was fun to implement, don't hesitate to propose more ;)

![95sxqv](https://github.com/user-attachments/assets/a0e12594-d7c5-4e92-b33a-b4478e0bb441)

Also I'm thinking of adding `mfa_serial` option such as:

```yaml
environments:
  dev:
    aws:
      assume_role: 
        role_arn: arn:aws:iam::111122223333:role/NovopsTestAssumeRole
        source_profile: novops-aws-test-identity-cache-load-timeout
        mfa_serial = arn:aws:iam::128716708097:mfa/cli-user
```

Would that prove useful?
