### ISSUE TITLE
Segmentation fault when trying to get hvault_kv2 value

### ISSUE THREAD

**Issue by bgounon** [PierreBeucher/novops#14]
Hello there, following our discussion, I thought having a recap here could be helpful :)

Here is my full `.novops.yml` config:
```
name: test

config:
  hashivault:
    address: https://kh.novavault.cloud
environments:
  test:
    variables:
    - name: TEST_KEY
      value:
        hvault_kv2:
          mount: "secret"
          path: "test"
          key: "foo"
```

To trigger the segfault, just try loading this config with novops:
```
$ novops-rust load -e test                                                              
Using workdir: "/run/user/1000/novops/test/test"
[1]    1719615 segmentation fault (core dumped)  novops-rust load -e test
```
Vault authentication (via `VAULT_TOKEN`)` is set and operational:
```
$ nix run nixpkgs#vault -- kv get -address https://kh.novavault.cloud -mount=secret test
=== Data ===
Key    Value
---    -----
foo    bar
```

By the way, I'm using `v0.3.0`:
```
$ novops-rust --version   
novops 0.3.0
```
