### ISSUE TITLE
SOPS disregards full path to encrypted file

### ISSUE THREAD

**Issue by depatl** [PierreBeucher/novops#140]
Novops disregards full path to encrypted files, looks like it appends it to the ${CWD}.

**Comment by PierreBeucher** [comment]
Hi, you mean that the path to encrypted file appended to your current working directory rather then being considered an absolute path ? 

Do you have an example `.novops.yml` to reproduce ?

**Comment by depatl** [comment]
yeah, this is exactly the case. 

```
---
config:
  default:
    environment: relmgt
environments:
  relmgt:
    variables:
      - name: CREDS_USERNAME
        value:
          sops:
            file: ~/.config/creds/release_management.yaml
            extract: '["cec"]["username"]'
```

if I execute `source <(novops load)` from ${CWD} it drops an error, sayin it cannot find `${cwd}/~/.config/creds/release_management.yaml`
