### ISSUE TITLE
Warning or error when variables or files are conflicting between modules

### ISSUE THREAD

**Issue by PierreBeucher** [PierreBeucher/novops#19]
When multiple modules are outputting the same variable or file Novops should generate a warning or error. For example:

```
environments:
  dev:
    aws:
      assume_role:
        role_arn: arn:aws:iam::111122223333:role/NovopsTestAssumeRole

    hashivault:
      aws:
        name: test_role
```

Would output the same `AWS_*` variables and one will override the others without warning.
