### ISSUE TITLE
ability to load "field" secrets

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#21]
hi,
I would like to be able to load secrets via novops with the equivalent of this command:
`vault kv get -mount=secret -field=my_password_name my-service/prod/secrets-prod.yaml`

This would be super practical to use novops in tandem with `sops publish` that uploads the whole file https://github.com/mozilla/sops#publishing-to-vault

**Comment by PierreBeucher** [comment]
I think it's already possible. Considering command above and a SOPS file containing secrets like:

```yaml
my_password_name: ENC[AES256_GCM,data:xxxx****,type:str]
```

And published to Vault at `my-service/prod/secrets-prod.yaml`, Novops config would be:

```yaml
environments:
  dev:
    variables:
    - name: PASSWORD
      value:
        hvault_kv2:
          mount: secret
          path: "my-service/prod/secrets-prod.yaml"
          key: my_password_name
```

In other words, what CLI calls `field`, Novops calls `key`. I used the term `key` as it's how it's called on UI:
![image](https://github.com/novadiscovery/novops/assets/5041481/98fd5c97-75eb-4b8e-8f47-b8870b7faf2f)

Though we may provide an alias `field` maybe?
