### ISSUE TITLE
use the exported name as default for the remote entry name

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#62]
if `name` is missing in the content entry, could we assume the global name as a default

```
      - name: PULUMI_CONFIG_PASSPHRASE
        content:
          hvault_kv2:
            path: toto/dev
            # name: PULUMI_CONFIG_PASSPHRASE # this doesn't work but I wish it would and novops would use the exported name `PULUMI_CONFIG_PASSPHRASE`  as a default
```
